# Generated by Django 3.2.20 on 2023-09-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230908_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/static/media/user.png', upload_to='profile_pictures/'),
        ),
    ]
