# Generated by Django 3.2.20 on 2023-09-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_background',
            field=models.ImageField(default='profile_picture_background/default.png', null=True, upload_to='profile_picture_background/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/default.png', null=True, upload_to='profile_picture/'),
        ),
    ]
