# Generated by Django 3.2.20 on 2023-09-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='user.png', null=True, upload_to='post_img/'),
        ),
    ]
