# Generated by Django 3.2.20 on 2023-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_picture_post',
            field=models.ImageField(null=True, upload_to='send_post_img/'),
        ),
    ]
