# Generated by Django 3.2.20 on 2023-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_profile_picture_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dair_img', models.ImageField(null=True, upload_to='dair_img/')),
                ('dair_video', models.FileField(upload_to='dair_videos/')),
            ],
        ),
    ]
