# Generated by Django 3.2.20 on 2023-09-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_dair'),
    ]

    operations = [
        migrations.AddField(
            model_name='dair',
            name='profile_picture_dair',
            field=models.ImageField(null=True, upload_to='send_dair_img/'),
        ),
        migrations.AlterField(
            model_name='dair',
            name='dair_video',
            field=models.FileField(null=True, upload_to='dair_videos/'),
        ),
    ]
