# Generated by Django 3.2.20 on 2023-10-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20231014_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dair',
            name='dair_created_date',
        ),
    ]
