# Generated by Django 3.2.20 on 2023-10-14 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_remove_dair_dair_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dair',
            name='dair_img',
            field=models.ImageField(null=True, upload_to='dair_img/'),
        ),
        migrations.AddField(
            model_name='dair',
            name='dair_video',
            field=models.FileField(null=True, upload_to='dair_videos/'),
        ),
        migrations.CreateModel(
            name='DairPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dair_img', models.ImageField(null=True, upload_to='dair_img/')),
                ('dair_video', models.FileField(null=True, upload_to='dair_videos/')),
                ('dair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairpost', to='post.dair')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
