# Generated by Django 3.2.20 on 2023-10-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20231014_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dair',
            name='dair_img',
        ),
        migrations.RemoveField(
            model_name='dair',
            name='dair_video',
        ),
    ]
