# Generated by Django 3.2.20 on 2023-10-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20231014_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='dair',
            name='dair_img',
            field=models.ImageField(null=True, upload_to='dair_img/'),
        ),
        migrations.AddField(
            model_name='dair',
            name='dair_video',
            field=models.FileField(null=True, upload_to='dair_videos/'),
        ),
        migrations.DeleteModel(
            name='DairPost',
        ),
    ]
