# Generated by Django 3.2.20 on 2023-10-14 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20231014_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='dair',
            name='dair_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
