# Generated by Django 3.2.20 on 2023-10-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_dair_dair_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dair',
            name='dair_created_date',
        ),
        migrations.AddField(
            model_name='dair',
            name='dair_img',
            field=models.ImageField(null=True, upload_to='dair_img/'),
        ),
        migrations.AddField(
            model_name='dair',
            name='dair_video',
            field=models.FileField(null=True, upload_to='dair_videos/'),
        ),
        migrations.DeleteModel(
            name='DairPost',
        ),
    ]
