# Generated by Django 3.2.20 on 2023-10-15 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20231014_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dair',
            name='dair_img',
        ),
        migrations.RemoveField(
            model_name='dair',
            name='dair_video',
        ),
        migrations.AddField(
            model_name='dair',
            name='dair_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
