# Generated by Django 3.2.20 on 2023-10-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_alter_dair_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dair_img', models.ImageField(null=True, upload_to='dair_img/')),
                ('dair_video', models.FileField(null=True, upload_to='dair_videos/')),
                ('dair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dair_posts', to='post.dair')),
            ],
        ),
    ]
