# Generated by Django 3.2.21 on 2023-10-16 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_dairpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dair',
            name='dair_created_date',
        ),
        migrations.AddField(
            model_name='dairpost',
            name='dair_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
