# Generated by Django 3.2.21 on 2023-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_dairpost_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairpost',
            name='dair_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
