# Generated by Django 3.2.21 on 2023-11-15 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_dairpost_dair_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairpost',
            name='dair_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
