# Generated by Django 3.2.19 on 2023-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(default='pgb.png', upload_to='media/images/'),
        ),
    ]
