# Generated by Django 3.2.19 on 2023-07-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(default='pgb.png', upload_to='images/'),
        ),
    ]
