# Generated by Django 3.2.20 on 2023-09-04 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_auto_20230904_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='friends',
            name='freinds',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_to', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='chat.User'),
        ),
    ]
