# Generated by Django 3.2.20 on 2023-09-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20230904_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='freinds',
            new_name='friends',
        ),
    ]
