# Generated by Django 3.2.20 on 2023-09-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_rename_freinds_friends_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='friends',
            new_name='profile',
        ),
    ]
