# Generated by Django 3.2.20 on 2023-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20230904_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(default='user.png', null=True, upload_to='images/'),
        ),
    ]
